/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subscriber;

import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;

/**
 *
 * @author ADMIN
 */
public class ListSensor extends javax.swing.JFrame {
//   protected ListArea listArea;
   protected String data;
    public static String HOSTNAME = "localhost";
    public static int PORT = 8080;
    public Socket connection;
    public DataOutputStream sentBuff;
    public DataInputStream recBuff;
    public final static int sensor = 0;
    public final static String MAC = "22:33:44:55:66:77";
    public ListArea.State state = ListArea.State.HANDSHAKE;
    public String receive;
    public String sendDatatoListSensor;
    enum State {
        HANDSHAKE,
        GET_SENSORS,
        SELECT_SENSOR,
        WAIT_DATA,
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getData() {
        return data;
    }

    /**
     * Creates new form ListSensor
     */
    public ListSensor() {
        try {
            connection = new Socket(HOSTNAME, PORT);
            sentBuff = new DataOutputStream(connection.getOutputStream());
            recBuff = new DataInputStream(new BufferedInputStream(connection.getInputStream()));

            JSONObject jo = new JSONObject();
            jo.put("sensor", sensor);
            jo.put("MAC", MAC);
            sentBuff.writeUTF(jo.toString());
            this.state = ListArea.State.GET_SENSORS;
            receive = recBuff.readUTF();
            System.out.println("FROM SERVER: " + receive);

        } catch (IOException ex) {
            System.err.println(ex);
        }
        initComponents();
    }

    public ListSensor(String data) {
        this.data = data;
        try {
            connection = new Socket(HOSTNAME, PORT);
            sentBuff = new DataOutputStream(connection.getOutputStream());
            recBuff = new DataInputStream(new BufferedInputStream(connection.getInputStream()));

            JSONObject jo = new JSONObject();
            jo.put("sensor", sensor);
            jo.put("MAC", MAC);
            sentBuff.writeUTF(jo.toString());
            this.state = ListArea.State.GET_SENSORS;
            receive = recBuff.readUTF();
            System.out.println("FROM SERVER: " + receive);
        } catch (IOException ex) {
            System.err.println(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        ArrayList<JButton> jButtons = new ArrayList<JButton>();
        System.out.println(this.data);
        JSONObject myjson = new JSONObject(this.data);
        JSONArray the_json_array = myjson.getJSONArray("devices");
        int size = the_json_array.length();
        for (int i=0; i<size; i++) {
            String s = the_json_array.getString(i);

            JSONObject MACS = new JSONObject(s);
            String mac = MACS.getString("MAC");
            System.out.println(mac);
            javax.swing.JButton jButton = new javax.swing.JButton();
            jButton.setText(mac);
            jButtons.add(jButton);
        }
         javax.swing.JButton jButton1;
         javax.swing.JButton jButton2;
         javax.swing.JButton jButton3;
         javax.swing.JButton jButton4;
         javax.swing.JLabel jLabel1;
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//        jButton1.setText("Thiet bi do nhiet T1");
//        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jButton1MouseClicked(evt);
//            }
//        });
//
//        jButton2.setText("Thiet bi do nhiet T2");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        jButton3.setText("Thiet bi do do am W1");
//        jButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton3ActionPerformed(evt);
//            }
//        });
//
//        jButton4.setText("Thiet bi do do am W2");

        jLabel1.setText("                Cac thiet bi tren dia ban");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSensor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify

    // End of variables declaration
}
