/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subscriber;

import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

/**
 *
 * @author ADMIN
 */
public class ListArea extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public static String HOSTNAME = "localhost";
    public static int PORT = 8080;
    public Socket connection;
    public DataOutputStream sentBuff;
    public DataInputStream recBuff;
    public final static int sensor = 0;
    public final static String MAC = "22:33:44:55:66:77";
    public ListArea.State state = ListArea.State.HANDSHAKE;
    public String receive;
    enum State {
        HANDSHAKE,
        GET_SENSORS,
        SELECT_SENSOR,
        WAIT_DATA,
    }

    public ListArea() {
        initComponents();
        try {
            connection = new Socket(HOSTNAME, PORT);
            sentBuff = new DataOutputStream(connection.getOutputStream());
            recBuff = new DataInputStream(new BufferedInputStream(connection.getInputStream()));
            state = State.HANDSHAKE;
            if(state == ListArea.State.HANDSHAKE) {
                JSONObject jo = new JSONObject();
                jo.put("sensor", sensor);
                jo.put("MAC", MAC);
                sentBuff.writeUTF(jo.toString());
                state = ListArea.State.GET_SENSORS;
            }
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }

    public void sendMessage(String location) throws IOException {
//        if(state == ListArea.State.HANDSHAKE) {
//            JSONObject jo = new JSONObject();
//            jo.put("sensor", sensor);
//            jo.put("MAC", MAC);
//            sentBuff.writeUTF(jo.toString());
//            state = ListArea.State.GET_SENSORS;
//        } else {
//            JSONObject obj = new JSONObject();
//            obj.put("location", location);
//            String jsonText = obj.toString();
//            System.out.println(jsonText);
//            sentBuff.writeUTF(jsonText);
//            receive = recBuff.readUTF();
//            System.out.println("FROM SERVER: " + receive);
//        }
        if(state != State.HANDSHAKE) {
            JSONObject obj = new JSONObject();
            obj.put("location", location);
            String jsonText = obj.toString();
            System.out.println(jsonText);
            sentBuff.writeUTF(jsonText);
            receive = recBuff.readUTF();
            System.out.println("FROM SERVER: " + receive);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        caugiay = new javax.swing.JButton();
        thanhxuan = new javax.swing.JButton();
        badinh = new javax.swing.JButton();
        hadong = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                       Du an lap trinh mang");

        caugiay.setText("Cau Giay");
        caugiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    caugiayMouseClicked(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        caugiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caugiayActionPerformed(evt);
            }
        });

        thanhxuan.setText("Thanh Xuan");
        thanhxuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    thanhxuanMouseClicked(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        thanhxuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhxuanActionPerformed(evt);
            }
        });

        badinh.setText("Ba Dinh");
        badinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    badinhMouseClicked(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        badinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badinhActionPerformed(evt);
            }
        });

        hadong.setText("Ha Dong");
        hadong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    hadongMouseClicked(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        hadong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hadongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(151, 151, 151)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(160, 160, 160)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(caugiay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(thanhxuan, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                        .addComponent(badinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(hadong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(caugiay)
                                .addGap(18, 18, 18)
                                .addComponent(thanhxuan)
                                .addGap(18, 18, 18)
                                .addComponent(badinh)
                                .addGap(18, 18, 18)
                                .addComponent(hadong)
                                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void caugiayActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void caugiayMouseClicked(java.awt.event.MouseEvent evt) throws IOException {
        String location = "Cau Giay";
        sendMessage(location);
//        new ListSensor().setVisible(true);
//        this.dispose();
        // TODO add your handling code here:
    }

    private void thanhxuanMouseClicked(java.awt.event.MouseEvent evt) throws IOException {
        // TODO add your handling code here:
        String location = "Thanh Xuan";
        sendMessage(location);
//        new ListSensor().setVisible(true);
//        this.dispose();
    }

    private void badinhMouseClicked(java.awt.event.MouseEvent evt) throws IOException {
        String location = "Ba Dinh";
        sendMessage(location);
        // TODO add your handling code here:
    }

    private void hadongMouseClicked(java.awt.event.MouseEvent evt) throws IOException {
        // TODO add your handling code here:
        String location = "Ha Dong";
        sendMessage(location);
    }

    private void thanhxuanActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void badinhActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void hadongActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton badinh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton caugiay;
    private javax.swing.JButton hadong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton thanhxuan;
    // End of variables declaration
}