/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subscriber;


import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONObject;
import subscriber.AplicationState;

import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class SensorDetail {
    public   String data;
    public String receive;
    public JFrame jFrame;
    public String MAC_Address;
    public Thread thread;
    int x_chan = 80;
    int y_chan = 80;
    int x_le = 300;
    int y_le = 80;
    int y_value = 80;
    public int data_length;
    /**
     * Creates new form DataDetailSensor
     */

    public SensorDetail() throws IOException {
        System.out.println(AplicationState.state);
        initComponents();


    }

    public SensorDetail(String MAC_Address) throws IOException {
        this.MAC_Address = MAC_Address;
        initComponents();
        System.out.println("1234"+AplicationState.state );
    }

    public String recMessage() throws IOException {
        String result = "";
        if (AplicationState.state == AplicationState.State.WAIT_DATA) {
            receive = AplicationState.recBuff.readUTF();
            result = receive;
        }

        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws IOException {
        jFrame = new JFrame("Sensor Detail");
        jFrame.setSize(600,500);
        jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jFrame.addWindowListener (new WindowAdapter() {
            public void windowClosing (WindowEvent e) {
                try {
                    AplicationState.connection.close();
                    AplicationState.sentBuff.close();
                    AplicationState.recBuff.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                thread.stop();
                jFrame.dispose();

            }
        });

        if (AplicationState.state == AplicationState.State.SELECT_SENSOR) {
            JSONObject obj = new JSONObject();
            obj.put("MAC", MAC_Address);
            String jsonText = obj.toString();
            System.out.println("abcd"+jsonText);
            AplicationState.sentBuff.writeUTF(jsonText);
            AplicationState.state = AplicationState.State.WAIT_DATA;
            receive = AplicationState.recBuff.readUTF();
            if(receive.equals("{}")) {
                data = "No data";
                JLabel jLabel = new JLabel(data);
                jLabel.setBounds(230,80,150,50);
                jFrame.add(jLabel, BorderLayout.NORTH);
            }
            else {
                data = receive;
                ArrayList<String> datas = new ArrayList<String>();
                ArrayList<String> temperature = new ArrayList<String>();
                ArrayList<String> asdfl = new ArrayList<String>();
                ArrayList<JLabel> jLabels = new ArrayList<JLabel>();
                JSONObject myjson = new JSONObject(this.data);
                JSONArray the_json_array = myjson.getJSONArray("data");
                int size = the_json_array.length();
                System.out.println(size);
                data_length = size;
                for (int i=0; i<size; i++) {
                    String s = the_json_array.getString(i);
                    JSONObject MACS = new JSONObject(s);
                    datas.add(MACS.getString("data"));
                    temperature.add(MACS.getString("temperature"));
                    asdfl.add(MACS.getString("asdfl"));
                    JLabel jl = new JLabel();
                    jl.setText("<html>"+MACS.getString("data")+"<br>"+MACS.getString("temperature")+"<br>"+MACS.getString("asdfl"));
                    jLabels.add(jl);
                }
                JLabel jLabel = new JLabel("Du lieu cua thiet bi");
                jLabel.setBounds(230,20,150,50);
                jFrame.add(jLabel, BorderLayout.NORTH);
                for(int i=0; i<jLabels.size(); i++) {
                    jLabels.get(i).setHorizontalAlignment(SwingConstants.CENTER);
                    jFrame.add(jLabels.get(i), BorderLayout.CENTER);
                    if(i%2==0) {
                        y_chan = y_chan+y_value*(i/2);
                        jLabels.get(i).setBounds(x_chan,y_chan,170,50);
                    }
                    else {
                        y_le = y_le+y_value*(i/2);
                        jLabels.get(i).setBounds(x_le,y_le,170,50);
                    }
                }
            }

            System.out.println("data " +receive);
        }
        thread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        String s = recMessage();
                        System.out.println(s);
                        JSONObject data_good_time = new JSONObject(s);
                        JLabel jl = new JLabel();
                        jl.setText("<html>"+data_good_time.getString("data")+"<br>"+data_good_time.getString("temperature")+"<br>"+data_good_time.getString("asdfl"));
                        jl.setHorizontalAlignment(SwingConstants.CENTER);
                        jFrame.add(jl, BorderLayout.CENTER);
                        if(data_length%2==0) {
                            y_chan = y_chan+y_value*(data_length/2);
                            jl.setBounds(x_chan,y_chan,170,50);
                        }
                        else {
                            y_le = y_le+y_value*(data_length/2);
                            jl.setBounds(x_le,y_le,170,50);
                        }
                        data_length++;
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    jFrame.setVisible(true);
                }
            }
        });
        thread.start();

        jFrame.setLayout(null);
        jFrame.setVisible(true);


    }// </editor-fold>



    /**
     * @param args the command line arguments
     */

}
